// AUTO-GENERATED by scripts/build-sprites.ts. Do not edit.
// Coverage: 2/24 species.
export const SPRITE_FILES: Record<string, string> = {
  rhinoceros_beetle: 'rhinoceros_beetle.svg',
  mantis: 'mantis.svg',
}
