import { readdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { arthropodList } from '@super-insect-battle/engine'

const here = dirname(fileURLToPath(import.meta.url))
const spritesDir = join(here, '..', 'public', 'sprites')
const manifestPath = join(here, '..', 'src', 'renderer', 'sprite-manifest.ts')

const SUPPORTED = ['.png', '.webp', '.svg']

function buildManifest(): void {
  const files = readdirSync(spritesDir)
  const byId = new Map<string, string>()

  for (const file of files) {
    const ext = SUPPORTED.find((e) => file.endsWith(e))
    if (!ext) continue
    byId.set(file.slice(0, -ext.length), file)
  }

  const entries = arthropodList
    .filter((a) => byId.has(a.id))
    .map((a) => `  ${a.id}: '${byId.get(a.id)}',`)
    .join('\n')

  const present = arthropodList.filter((a) => byId.has(a.id)).length
  const missing = arthropodList
    .filter((a) => !byId.has(a.id))
    .map((a) => a.id)

  const content = `// AUTO-GENERATED by scripts/build-sprites.ts. Do not edit.
// Coverage: ${present}/${arthropodList.length} species.
export const SPRITE_FILES: Record<string, string> = {
${entries}
}
`

  writeFileSync(manifestPath, content)

  console.log(`Sprite manifest written: ${present}/${arthropodList.length}`)
  if (missing.length > 0) {
    console.log(`Missing sprites (rectangle fallback): ${missing.join(', ')}`)
  }
}

buildManifest()
