import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse } from 'yaml'

interface RoomYaml {
  id: string
  name: string
  description: string
  exits: Record<string, string>
  hasWildEncounters: boolean
  wildInsects?: string[]
}

interface AreaYaml {
  id: string
  name: string
  rooms: RoomYaml[]
}

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const AREAS_DIR = path.join(__dirname, '../data/areas')
const OUTPUT_FILE = path.join(__dirname, '../src/world/rooms.generated.ts')

function loadAreaFiles(): AreaYaml[] {
  const files = fs.readdirSync(AREAS_DIR).filter((f) => f.endsWith('.yml'))
  const areas: AreaYaml[] = []

  for (const file of files) {
    const content = fs.readFileSync(path.join(AREAS_DIR, file), 'utf-8')
    const area = parse(content) as AreaYaml
    areas.push(area)
  }

  return areas
}

function generateTypeScript(areas: AreaYaml[]): string {
  const allRooms: Record<string, RoomYaml> = {}

  for (const area of areas) {
    for (const room of area.rooms) {
      allRooms[room.id] = room
    }
  }

  const roomEntries = Object.entries(allRooms)
    .map(([id, room]) => {
      const exits = JSON.stringify(room.exits, null, 2).replace(/\n/g, '\n    ')
      const wildInsects = room.wildInsects
        ? JSON.stringify(room.wildInsects)
        : 'undefined'

      return `  ${id}: {
    id: '${id}',
    name: '${room.name}',
    description: ${JSON.stringify(room.description.trim())},
    exits: ${exits},
    hasWildEncounters: ${room.hasWildEncounters},
    wildInsects: ${wildInsects},
  }`
    })
    .join(',\n\n')

  return `// Auto-generated from data/areas/*.yml
// Do not edit this file directly

import type { Room } from '../game/types'

export const generatedRooms: Record<string, Room> = {
${roomEntries},
}
`
}

function main(): void {
  console.log('Loading area files...')
  const areas = loadAreaFiles()

  console.log(`Found ${areas.length} areas:`)
  for (const area of areas) {
    console.log(`  - ${area.name} (${area.rooms.length} rooms)`)
  }

  console.log('Generating TypeScript...')
  const typescript = generateTypeScript(areas)

  fs.writeFileSync(OUTPUT_FILE, typescript, 'utf-8')
  console.log(`Generated: ${OUTPUT_FILE}`)
}

main()
